### ISSUE TITLE
Auto suspend & roles

### ISSUE THREAD

**Issue by abudata** [Mashey/snowflake_resources#3]
**On defining auto suspend for the warehouses:**
I think it would be better to reduce `auto_suspend` from 60 to 5 minutes. This is what I read as a best practice on the Snowflake website. 
> If you enable auto-suspend, we recommend setting it to a low value (e.g. 5 or 10 minutes or less) because Snowflake utilizes per-second billing. This will help keep your warehouses from running (and consuming credits) when not in use.

**On roles:**
I would not link roles to positions/titles such as `DATA_ANALYST`, etc in [here](https://github.com/Mashey/snowflake_resources/blob/main/snowflake_setup.sql#L38). I'd think that we should have the following roles as we discussed during our meeting.

- LOADER
- TRANSFORMER
- ADMIN_REPORTER
- REPORTER
- ENGINEER

**Comment by iEv0lv3** [comment]
@abudata - thank you for the feedback!

- Great point about controlling costs through effective implementation of `auto_suspend`!
   - I agree with @alerrian that we should implement an `auto_suspend` time of 1 minute
- RE: Role names
  - Understood. As we started developing we found it helpful to identify who would actually be granted a role in most Snowflake environments, but we'd be happy to update the role names in our next PR per your request!

**Comment by abudata** [comment]
@alerrian Got it. Thanks for letting me know that the `auto_suspend` is based on seconds. It does make sense to be at 60 seconds rather than 5 minutes. 
@iEv0lv3 Sounds good and thanks. Let me know if you want me to open a PR related to the roles names.

**Comment by iEv0lv3** [comment]
@abudata - all good, thank you! We updated the names in PR #4

**Comment by abudata** [comment]
Awesome! I am closing this ticket.
